// SPDX-License-Identifier: MIT
//ProjectRegistry.sol
pragma solidity ^0.8.19;

contract ProjectRegistry {
    struct Project {
        string projectId;
        address ngo;
        string plantationHash;
        uint256 createdAt;
        bool exists;
        bool isVerified;
        bool isListed;
    }

    mapping(string => Project) private _projects;

    event ProjectRegistered(string indexed projectId, address indexed ngo);
    event ProjectStatusUpdated(string indexed projectId, bool verified, bool listed);

    /**
     * @notice Register a new project on-chain. Called by backend after storing full data off-chain.
     * @param projectId Unique project identifier (generated by backend)
     * @param plantationHash SHA256 (or similar) hash of the plantation JSON stored off-chain
     */
    function registerProject(string calldata projectId, string calldata plantationHash) external {
        require(!_projects[projectId].exists, "Project already registered");

        _projects[projectId] = Project({
            projectId: projectId,
            ngo: msg.sender,
            plantationHash: plantationHash,
            createdAt: block.timestamp,
            exists: true,
            isVerified: false,
            isListed: false
        });

        emit ProjectRegistered(projectId, msg.sender);
    }

    /**
     * @notice Update simple status flags. (You may restrict this by access control later.)
     * @param projectId Project to update
     * @param verified Whether project is verified (set by verifier/backend workflow)
     * @param listed Whether project is listed (optional business flag)
     */
    function updateStatus(string calldata projectId, bool verified, bool listed) external {
        require(_projects[projectId].exists, "Project not found");

        Project storage p = _projects[projectId];
        p.isVerified = verified;
        p.isListed = listed;

        emit ProjectStatusUpdated(projectId, verified, listed);
    }

    /**
     * @notice Check if project exists (useful for other contracts).
     * @param projectId Project identifier
     */
    function projectExists(string calldata projectId) external view returns (bool) {
        return _projects[projectId].exists;
    }

    /**
     * @notice Get basic project details.
     * @param projectId Project identifier
     * @return ngo NGO wallet address
     * @return plantationHash Hash stored on-chain
     * @return createdAt timestamp of registration
     * @return isVerified verification flag
     * @return isListed listing flag
     */
    function getProject(string calldata projectId)
        external
        view
        returns (
            address ngo,
            string memory plantationHash,
            uint256 createdAt,
            bool isVerified,
            bool isListed
        )
    {
        require(_projects[projectId].exists, "Project not found");
        Project memory p = _projects[projectId];
        return (p.ngo, p.plantationHash, p.createdAt, p.isVerified, p.isListed);
    }
}